package com.sohu.sur.model.admin;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.sohu.sur.util.DateUtils;
import com.sohu.sur.util.EnumUtils;
import com.sohu.sur.util.PicUtils;



/**
 * SucUser generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class SucUser  implements java.io.Serializable {
    // Fields    

    private Long id;
    private String sucPassport;//帐户名
    private String sucPassportArray;
    private String sucName;//姓名
    private Integer sex;//性别
    private Date birthday;//生日
    private String position;//住址
    private String tel;//电话
    private Date createtime;//创建时间
    private Date operatortime;//最后操作时间
    private Integer pub;//是否显示
    private Integer state;//帐户状态
    private Integer postalCode;//邮编
    private Integer province;//省份
    private Integer city;//城市
    private String nickName;//昵称
    private String pic;//用户头像
    private String bigPic;
    private String sid;//系统源ID
   
    
//  基础信息是否完整
    private Integer isComplete;
    //专有信息是否完整
    private Integer extendIsComplete;
    
    //前端用户注册使用，验证码
    private String checkCode;
    //存放用户当前所在域
    private Long regionId;

    
    private Integer num;//获取用户信息条数
    private Integer pageCount;//当前页数
    private Integer pageNo;//当前页
    private String status;//获取用户信息状态
    

	
	
	/**
	 * 创建时间范围查询
	 */
	private String startCreateTime;
	private String endCreateTime;
	
    /**
     * passport相关属性
     * 
     */
    private String sucPassportMd5;
    private String sucPassword;//用户密码
    private String newSucPassword;//修改密码时使用
    private String appId;//passport对应的应用ID
    private Long currentTime;//时间戳
    private String md5Pass;//md5
    private String createip;//
	private String answer;
	private String newAnswer;
	private String question;
	private String newQuestion;
	
	//说两句
	private Long commentId;
	
	/**
	 * region
	 */
	private String url;
	
	/**
	 * 接口调用，模糊查询
	 */
	private String keyWords;
	
	/**
	 * 个人中心后台调用-下拉菜单选择条件
	 */
	private String con;
	
	/**
	 * 当前登录来源-系统源ID
	 */
	private Integer loginSid;
	
	/**
	 * 用户图表统计条件
	 */
	private String stat;
	
	private String flag;
	
    // Constructors

    public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/** default constructor */
    public SucUser() {
    }
    
    /** full constructor */
    public SucUser(Long id, String sucPassport, String sucPassportMd5, String sucName, Integer sex, 
    		Date birthday, String position, 
    		String tel, Date createtime, 
    		Date operatortime, Integer pub, Integer state,
    		Integer postalCode,Integer city,Integer province,
    		String sucPassword,String pic,Integer isComplete,
    		String bigPic,String sid) {
    	
        this.id = id;
        this.sucName = sucName;
        this.sex = sex;
        this.birthday = birthday;
        this.position = position;
        this.tel = tel;
        this.createtime = createtime;
        this.operatortime = operatortime;
        this.pub = pub;
        this.state = state;
        this.postalCode = postalCode;
        this.sucPassport = sucPassport;
        this.sucPassportMd5 = sucPassportMd5;
        this.sucPassword = sucPassword;
        this.city = city;
        this.province = province;
        this.pic = pic;
        this.isComplete = isComplete;
        this.bigPic = bigPic;
        this.sid = sid;
        
    }
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSucName() {
        return this.sucName;
    }
    
    public void setSucName(String sucName) {
        this.sucName = sucName;
    }

    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getOperatortime() {
        return this.operatortime;
    }
    
    public void setOperatortime(Date operatortime) {
        this.operatortime = operatortime;
    }

    public Integer getPub() {
        return this.pub;
    }
    
    public void setPub(Integer pub) {
        this.pub = pub;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

	public Integer getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}
	
	private String statusString;//状态
	
	public String getStatusString() {
		
		if(state != null)
		{
			if(state == EnumUtils.status.正常.ordinal())
			{
				statusString = EnumUtils.status.正常.name();
			} else if(state == EnumUtils.status.删除.ordinal())
			{
				statusString = EnumUtils.status.删除.name();
			} else if(state == EnumUtils.status.不确定.ordinal())
			{
				statusString = EnumUtils.status.不确定.name();
			}			
		}
		
		return statusString;
	}
	
	private Map sexMap;//
    private Map pubMap;//
    private Map stateMap;//state
    private Map freezeMap;
    
    public Map getFreezeMap() {
    	freezeMap = EnumUtils.getFreezeMap();
  		return freezeMap;
  	}
    
    public Map getSexMap() {
  		sexMap = EnumUtils.getSexMap();
  		return sexMap;
  	}
    
    public Map getStateMap() {
    	stateMap = EnumUtils.getStatusMap();
 		return stateMap;
 	}
 	
 	public Map getPubMap() {
 		pubMap = EnumUtils.getPubMap();
 		return pubMap;
 	}

 	public String getLocaleCreateTime(){
 		if(this.getCreatetime()!=null){
 			return DateUtils.getTodayDate(this.getCreatetime(),"yyyy-MM-dd");
 		}
 		
 		return null;
 	}
 	
 	public String getLocaleOperatorTime(){
 		if(this.getOperatortime()!=null){
 			return this.getOperatortime().toLocaleString();
 		}
 		
 		return null;
 	}
 	
 	public String getLocaleBirthday(){
 		
 		if(this.getBirthday()!=null&&this.getBirthday().toLocaleString().length()>=10){
 			return DateUtils.getTodayDate(this.getBirthday(),"yyyy-MM-dd");
 		}
 		
 		return null;
 	}

	public String getSucPassport() {
		return sucPassport;
	}

	public void setSucPassport(String sucPassport) {
		this.sucPassport = sucPassport;
	}

	public String getCheckCode() {
		return checkCode;
	}

	public void setCheckCode(String checkCode) {
		this.checkCode = checkCode;
	}

	public Integer getCity() {
		return city;
	}

	public void setCity(Integer city) {
		this.city = city;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getSucPassportMd5() {
		return sucPassportMd5;
	}

	public void setSucPassportMd5(String sucPassportMd5) {
		this.sucPassportMd5 = sucPassportMd5;
	}

	public String getSucPassword() {
		return sucPassword;
	}

	public void setSucPassword(String sucPassword) {
		this.sucPassword = sucPassword;
	}


	public Long getRegionId() {
		return regionId;
	}

	public void setRegionId(Long regionId) {
		this.regionId = regionId;
	}

	public String getNewSucPassword() {
		return newSucPassword;
	}

	public void setNewSucPassword(String newSucPassword) {
		this.newSucPassword = newSucPassword;
	}


	public Integer getProvince() {
		return province;
	}

	public void setProvince(Integer province) {
		this.province = province;
	}


	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public Long getCurrentTime() {
		return currentTime;
	}

	public void setCurrentTime(Long currentTime) {
		this.currentTime = currentTime;
	}

	public String getMd5Pass() {
		return md5Pass;
	}

	public void setMd5Pass(String md5Pass) {
		this.md5Pass = md5Pass;
	}

	public String getCreateip() {
		return createip;
	}

	public void setCreateip(String createip) {
		this.createip = createip;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getNewAnswer() {
		return newAnswer;
	}

	public void setNewAnswer(String newAnswer) {
		this.newAnswer = newAnswer;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getNewQuestion() {
		return newQuestion;
	}

	public void setNewQuestion(String newQuestion) {
		this.newQuestion = newQuestion;
	}

	public String getPic() {
		return pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public Integer getIsComplete() {
		return isComplete;
	}

	public void setIsComplete(Integer isComplete) {
		this.isComplete = isComplete;
	}
	
	public Integer getExtendIsComplete() {
		return extendIsComplete;
	}

	public void setExtendIsComplete(Integer extendIsComplete) {
		this.extendIsComplete = extendIsComplete;
	}

	public String getBigPic() {
		return bigPic;
	}

	public void setBigPic(String bigPic) {
		this.bigPic = bigPic;
	}
	
	public String getHeadPic(String defPic){
		if(pic!=null&&!pic.equals("")){
			return PicUtils.getPicServerPathS(this.id)+this.pic;
			//return this.pic;
		}
		
		return PicUtils.getPicServerPathS(this.id)+ defPic;
	}
	
	public String getBigHeadPic(String defPic){
		if(bigPic!=null&&!bigPic.equals("")){
			return PicUtils.getPicServerPathS(this.id)+this.bigPic;
			//return this.bigPic;
		}
		
		return PicUtils.getPicServerPathS(this.id)+ defPic;
	}
	
	public String getNickName(String defName){
		if(nickName!=null&&!nickName.equals("")){
			return this.nickName;
		}
		return defName;
	}
	
	private String faz;
	private String fuz;
	private String fazName;
	private String fuzName;
	
	
	
	public void setFazName(String fazName) {
		this.fazName = fazName;
	}

	public void setFuzName(String fuzName) {
		this.fuzName = fuzName;
	}
	
	public void setFaz(String faz) {
		this.faz = faz;
	}
	
	public void setFuz(String fuz) {
		this.fuz = fuz;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEndCreateTime() {
		return endCreateTime;
	}

	public void setEndCreateTime(String endCreateTime) {
		this.endCreateTime = endCreateTime;
	}

	public String getStartCreateTime() {
		return startCreateTime;
	}

	public void setStartCreateTime(String startCreateTime) {
		this.startCreateTime = startCreateTime;
	}

	public Integer getPageCount() {
		return pageCount;
	}

	public void setPageCount(Integer pageCount) {
		this.pageCount = pageCount;
	}

	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public String getKeyWords() {
		return keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	public Long getCommentId() {
		return commentId;
	}

	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	public String getCon() {
		return con;
	}

	public void setCon(String con) {
		this.con = con;
	}

	public Integer getLoginSid() {
		return loginSid;
	}

	public void setLoginSid(Integer loginSid) {
		this.loginSid = loginSid;
	}

	public String getStat() {
		return stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}


	public String getSucPassportArray() {
		return sucPassportArray;
	}

	public void setSucPassportArray(String sucPassportArray) {
		this.sucPassportArray = sucPassportArray;
	}



}